"$schema" = 'https://starship.rs/config-schema.json'

format = """
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
${custom.dir_close}\
$git_branch\
$git_status\
${custom.git_close}\
${custom.git_to_tech}\
${custom.dir_to_tech}\
$nodejs\
$rust\
$golang\
$php\
$python\
${custom.tech_close}\
 $cmd_duration\n\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[](fg:#769ff0 bg:#394260)[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[$all_status$ahead_behind](fg:#769ff0 bg:#394260)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[php]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[python]
symbol = "🐍 "
style = "bg:#212736"
format = '[ $symbol$virtualenv ](fg:#769ff0 bg:#212736)'
detect_folders = [".venv", "venv", "venv311"]

[cmd_duration]
min_time = 2000
format = "[ took $duration](bold yellow) "

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[custom.dir_close]
command = "printf '%s' ''"
when = '''! git rev-parse --is-inside-work-tree >/dev/null 2>&1 && [ ! -d .venv ] && [ ! -d venv ] && [ ! -d venv311 ] && [ ! -f package.json ] && [ ! -f Cargo.toml ] && [ ! -f go.mod ] && [ ! -f composer.json ]'''
format = "[](fg:#769ff0)"
shell = ["sh"]

[custom.git_close]
command = "printf '%s' ''"
when = '''git rev-parse --is-inside-work-tree >/dev/null 2>&1 && [ ! -d .venv ] && [ ! -d venv ] && [ ! -d venv311 ] && [ ! -f package.json ] && [ ! -f Cargo.toml ] && [ ! -f go.mod ] && [ ! -f composer.json ]'''
format = "[](fg:#394260)"
shell = ["sh"]

[custom.git_to_tech]
command = "printf '%s' ''"
when = '''git rev-parse --is-inside-work-tree >/dev/null 2>&1 && { [ -d .venv ] || [ -d venv ] || [ -d venv311 ] || [ -f package.json ] || [ -f Cargo.toml ] || [ -f go.mod ] || [ -f composer.json ]; }'''
format = "[](fg:#394260 bg:#212736)"
shell = ["sh"]

[custom.dir_to_tech]
command = "printf '%s' ''"
when = '''! git rev-parse --is-inside-work-tree >/dev/null 2>&1 && { [ -d .venv ] || [ -d venv ] || [ -d venv311 ] || [ -f package.json ] || [ -f Cargo.toml ] || [ -f go.mod ] || [ -f composer.json ]; }'''
format = "[](fg:#769ff0 bg:#212736)"
shell = ["sh"]

[custom.tech_close]
command = "printf '%s' ''"
when = '''[ -d .venv ] || [ -d venv ] || [ -d venv311 ] || [ -f package.json ] || [ -f Cargo.toml ] || [ -f go.mod ] || [ -f composer.json ]'''
format = "[](fg:#212736)"
shell = ["sh"]
